version: "3.1"

services:
  nginx:
    image: nginx:1.13
    container_name: atm-nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/atm.local
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: atm-php-fpm
    working_dir: /var/www/html/atm.local
    command: sh ./docker/php-fpm/script/init.sh
    volumes:
      - ./:/var/www/html/atm.local
    depends_on:
      - mysql
  mysql:
    build:
      context: ./docker/database
    container_name: atm-mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/database/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "atm"
      MYSQL_USER: "atm"
      MYSQL_PASSWORD: "atm"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
